Repository pinafrica/awlo-ga-registration-frontend, pull requests merged in 2021-01, with the labels that each got.

#3 Location input
  index.html
  js/main.js
  styles/main.css
Labels: enhancement

#8 feat: add International Telephone Input
  img/flags.png
  img/flags@2x.png
  index.html
  js/intlTelInput.min.js
  js/main.js
  js/utils.js
  styles/intlTelInput.min.css
  styles/main.css
Labels: enhancement

#9 style: enhance submit-button look on submit
  js/main.js
  styles/main.css
Labels: enhancement

#10 feat: implement form validation before form submission
  js/main.js
Labels: enhancement

#14 style: generate and add site favicon
  img/android-chrome-192x192.png
  img/android-chrome-512x512.png
  img/apple-touch-icon.png
  img/favicon-16x16.png
  img/favicon-32x32.png
  img/favicon.ico
  img/site.webmanifest
  index.html
Labels: enhancement

#16 fix: wrong phone number input name
  js/main.js
Labels: bug

#15 feat: add copyright to page
  index.html
  js/main.js
  styles/main.css
Labels: enhancement

#18 feat: add partnership section
  index.html
  styles/main.css
Labels: enhancement

#17 fix: comment code and fix issues with button spinner displaying multiple times on successive click and fullNumber returning empty.
  index.html
  js/main.js
Labels: bug

#24 feat: add meta tags and color address bar on mobile
  index.html
Labels: enhancement, good first issue

#25 feat: add close modal functionality
  js/main.js
Labels: enhancement
